
package cxf2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SoapServer", targetNamespace = "http://notice.server.soap.common.exchange.autinform.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SoapServer {

	/**
	 * 
	 * @return returns boolean
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "success", partName = "success")
	public boolean getAuthentication() throws Fault;

	/**
	 * 
	 * @param docId
	 * @return returns java.lang.String
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeXml", partName = "noticeXml")
	public String getNoticeXml(@WebParam(name = "docId", partName = "docId") long docId) throws Fault;

	/**
	 * 
	 * @param publishDate
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getNoticeList(
			@WebParam(name = "publishDate", partName = "publishDate") XMLGregorianCalendar publishDate) throws Fault;

	/**
	 * 
	 * @param publishDate
	 * @param category
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getNoticeListForCategory(@WebParam(name = "category", partName = "category") String category,
			@WebParam(name = "publishDate", partName = "publishDate") XMLGregorianCalendar publishDate) throws Fault;

	/**
	 * 
	 * @param searchXml
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getSearchNoticeList(@WebParam(name = "searchXml", partName = "searchXml") String searchXml)
			throws Fault;

	/**
	 * 
	 * @param searchXml
	 * @return returns java.lang.String
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public String getSearchNoticeCount(@WebParam(name = "searchXml", partName = "searchXml") String searchXml)
			throws Fault;

	/**
	 * 
	 * @param searchXml
	 * @param arg1
	 * @return returns java.lang.String
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public String getSearchNoticeXml(@WebParam(name = "searchXml", partName = "searchXml") String searchXml,
			@WebParam(name = "arg1", partName = "arg1") String arg1) throws Fault;

	/**
	 * 
	 * @param category
	 * @param status
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getActualCantonNoticeListForCategoryWithStatus(
			@WebParam(name = "category", partName = "category") String category,
			@WebParam(name = "status", partName = "status") String status) throws Fault;

	/**
	 * 
	 * @param category
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getActualCantonNoticeListForCategory(
			@WebParam(name = "category", partName = "category") String category) throws Fault;

	/**
	 * 
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getActualCantonNoticeList() throws Fault;

	/**
	 * 
	 * @param publishDate
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getPublishedNoticeList(
			@WebParam(name = "publishDate", partName = "publishDate") XMLGregorianCalendar publishDate) throws Fault;

	/**
	 * 
	 * @param docId
	 * @return returns cxf2.Provider
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "provider", partName = "provider")
	public Provider getProviderFromNotice(@WebParam(name = "docId", partName = "docId") long docId) throws Fault;

	/**
	 * 
	 * @param publishDate
	 * @return returns java.lang.String
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeXmls", partName = "noticeXmls")
	public String getNoticeXmls(
			@WebParam(name = "publishDate", partName = "publishDate") XMLGregorianCalendar publishDate) throws Fault;

	/**
	 * 
	 * @param docId
	 * @return returns byte[]
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "pdf", partName = "pdf")
	public byte[] getNoticePdf(@WebParam(name = "docId", partName = "docId") long docId) throws Fault;

	/**
	 * 
	 * @param publishDate
	 * @param subscriptionId
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getNoticeListForSubscriber(
			@WebParam(name = "publishDate", partName = "publishDate") XMLGregorianCalendar publishDate,
			@WebParam(name = "subscriptionId", partName = "subscriptionId") int subscriptionId) throws Fault;

	/**
	 * 
	 * @param publishDateFrom
	 * @param publishDateTo
	 * @param subscriptionId
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getNoticeListForSubscriberDateRange(
			@WebParam(name = "publishDateFrom", partName = "publishDateFrom") XMLGregorianCalendar publishDateFrom,
			@WebParam(name = "publishDateTo", partName = "publishDateTo") XMLGregorianCalendar publishDateTo,
			@WebParam(name = "subscriptionId", partName = "subscriptionId") int subscriptionId) throws Fault;

	/**
	 * 
	 * @param publishDate
	 * @param category
	 * @param status
	 * @return returns cxf2.LongArray
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeList", partName = "noticeList")
	public LongArray getNoticeListForCategoryWithStatus(
			@WebParam(name = "category", partName = "category") String category,
			@WebParam(name = "status", partName = "status") String status,
			@WebParam(name = "publishDate", partName = "publishDate") XMLGregorianCalendar publishDate) throws Fault;

	/**
	 * 
	 * @param docId
	 * @return returns java.lang.String
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "noticeHtml", partName = "noticeHtml")
	public String getNoticeHtml(@WebParam(name = "docId", partName = "docId") long docId) throws Fault;

	/**
	 * 
	 * @param docId
	 * @return returns byte[]
	 * @throws Fault
	 */
	@WebMethod
	@WebResult(name = "file", partName = "file")
	public byte[] getAttachment(@WebParam(name = "docId", partName = "docId") long docId) throws Fault;

}
