
package cxf2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SoapServerService service = new SoapServerService();
* SoapServer portType = service.getSoapServerPort();
* portType.getAuthentication(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SoapServerService", targetNamespace = "http://notice.server.soap.common.exchange.autinform.de/", wsdlLocation = "https://www.simap.ch/shabforms/soapserver?wsdl")
public class SoapServerService extends Service {

	private final static URL SOAPSERVERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(cxf2.SoapServerService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cxf2.SoapServerService.class.getResource(".");
			url = new URL(baseUrl, "https://www.simap.ch/shabforms/soapserver?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'https://www.simap.ch/shabforms/soapserver?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SOAPSERVERSERVICE_WSDL_LOCATION = url;
	}

	public SoapServerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SoapServerService() {
		super(SOAPSERVERSERVICE_WSDL_LOCATION,
				new QName("http://notice.server.soap.common.exchange.autinform.de/", "SoapServerService"));
	}

	/**
	 * 
	 * @return returns SoapServer
	 */
	@WebEndpoint(name = "SoapServerPort")
	public SoapServer getSoapServerPort() {
		return super.getPort(new QName("http://notice.server.soap.common.exchange.autinform.de/", "SoapServerPort"),
				SoapServer.class);
	}

}
